### ISSUE TITLE
Regression: function literal parsed as struct initializer

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/libdparse#316] opened 2018-11-06 11:22 UTC
As I was starting to update DFMT to libdparse 0.10.x, I stumbled upon a regression in libdparse: with the code `auto fun = {int i;};`, the braces seem to be considered as a struct initializer instead of a function literal, causing wrong formatting.
Git bisect tells me that this started with e6c83b2174ed41259be3caa8bbbd593f87ff87f0

**Comment by BBasile** [comment] 2018-11-06 11:31
The commit did something correct so to fix the regression it's rather expression parsing that must tweaked (i.e do not revert this one since it fixed that fact that basic types were seen as valid primary expressions).

**Comment by BBasile** [comment] 2018-11-06 11:36
I can confirm since i have D-Scanner built with dparse 0.10.4, here is that ast

```
<declaration>
<variableDeclaration>
<autoDeclaration>
<storageClasses>
<storageClass>
<auto/>
</storageClass>
</storageClasses>
<autoDeclarationPart>
<item>
<name line="3">fun</name>
<initializer>
<nonVoidInitializer>
<structInitializer>
<structMemberInitializers>
</structMemberInitializers>
</structInitializer>
</nonVoidInitializer>
</initializer>
</item>
</autoDeclarationPart>
</autoDeclaration>
</variableDeclaration>
</declaration>
```

**Comment by LaurentTreguier** [comment] 2018-11-06 11:51
It wasn't my intention to simply revert it; since the commit message does say that it's fixing something

**Comment by BBasile** [comment] 2018-11-06 12:17
The fix must be done in `parseNonVoidInitializer`. For now it tries to see if there's an expression between braces. If so then it considers braces as `AssignExpression` (which will contain a function literal) otherwise as a `StructInitializer`. #170 was badly fixed.

**Comment by BBasile** [comment] 2018-11-06 12:20
I think that going to the closing brace, then looking if the previous is a semicolon will tell for sure if this is a struct init or not.

**Closed** 2018-11-06 15:34 UTC
Labels: bug
